### ISSUE TITLE
Upgrade to the latest version of aemsync

### ISSUE THREAD

**Issue by arthurcavallari** [kevinweber/aem-front#10]
aemsync is up to version 4.0.0, and aem-front is still using 1.1.1

On AEM 6.4+, the aemsync packages are not being deleted from the package manager

**Comment by kevinweber** [comment]
I'm not sure what you mean… What version of AEM Front are you using?
Looking at https://github.com/kevinweber/aem-front/blob/master/package.json#L20, `4.0.0-rc1` is being used. Feel free to make a PR to update whatever needs to be updated.

**Comment by arthurcavallari** [comment]
Oh that is embarrassing, nevermind. I could swear I was using the latest. Carry on with the good work :)
