### ISSUE TITLE
Allow multiple targets

### ISSUE THREAD

**Issue by nedzvedz** [kevinweber/aem-front#5]
Hello @kevinweber ,

At the `aem-sync.js` file there are a few lines of code, which exit script execution if multiple targets were provided:
```
  if (targets.length > 1) {
    console.log(`You've provided multiple targets. Only the first one is used by BrowserSync.`);
    return;
  }
```

As for me it's fine that only one target will be used by browser sync, but I still would like to sync changes to both targets (author and publish). Please let me know if this `return` statement was intentional and contains some logic behind, otherwise I can create a PR to allow multiple targets.

Thanks,
Vitali

**Comment by kevinweber** [comment]
Hi @nedzvedz,
I assume that I had a reason for this… Maybe supporting multiple targets added more complexity than I was willing to deal with back then? [I wrote the first version pretty much overnight…]

If you can create a PR, I'd be happy to review, merge and publish your enhancements.

Best,
Kevin

**Comment by nedzvedz** [comment]
Hi @kevinweber,
Please take a look at this PR https://github.com/kevinweber/aem-front/pull/6

Thanks,
Vitali

**Comment by kevinweber** [comment]
PR #6 is merged.
